import { Restaurant, Order, Reservation, InventoryItem } from './types';

// Mock Restaurants Data
export const mockRestaurants: Restaurant[] = [
  {
    id: '1',
    name: 'The Gourmet Kitchen',
    description: 'A fine dining experience with a mix of international cuisines prepared by world-class chefs.',
    address: '123 Foodie Street, Culinary District',
    cuisineType: ['Italian', 'French'],
    rating: 4.8,
    priceRange: '$$$',
    openingHours: {
      opening: '11:00',
      closing: '22:00',
    },
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80',
    phoneNumber: '555-123-4567',
    email: 'info@gourmetkitchen.com',
    capacity: 80,
    availableForEvents: true,
  },
  {
    id: '2',
    name: 'Spice Avenue',
    description: 'Authentic Indian cuisine with traditional recipes and modern presentation.',
    address: '456 Spice Road, Flavor Town',
    cuisineType: ['Indian', 'Asian Fusion'],
    rating: 4.5,
    priceRange: '$$',
    openingHours: {
      opening: '12:00',
      closing: '23:00',
    },
    image: 'https://images.unsplash.com/photo-1517644493876-7864565e3bf9?w=600&q=80',
    phoneNumber: '555-987-6543',
    email: 'contact@spiceavenue.com',
    capacity: 60,
    availableForEvents: true,
  },
  {
    id: '3',
    name: 'Urban Plate',
    description: 'Modern American cuisine focusing on local ingredients and seasonal dishes.',
    address: '789 Local Lane, Downtown',
    cuisineType: ['American', 'New American'],
    rating: 4.2,
    priceRange: '$$',
    openingHours: {
      opening: '10:00',
      closing: '21:00',
    },
    image: 'https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?w=600&q=80',
    phoneNumber: '555-456-7890',
    email: 'hello@urbanplate.com',
    capacity: 50,
    availableForEvents: false,
  },
  {
    id: '4',
    name: 'Sushi Sensation',
    description: 'Premium Japanese sushi and sashimi prepared by expert chefs using fresh ingredients.',
    address: '101 Ocean Drive, Seaside',
    cuisineType: ['Japanese', 'Sushi'],
    rating: 4.9,
    priceRange: '$$$$',
    openingHours: {
      opening: '17:00',
      closing: '23:00',
    },
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&q=80',
    phoneNumber: '555-234-5678',
    email: 'info@sushisensation.com',
    capacity: 40,
    availableForEvents: true,
  },
  {
    id: '5',
    name: 'Pasta Paradise',
    description: 'Family-style Italian restaurant specializing in homemade pasta and traditional recipes.',
    address: '202 Pasta Place, Little Italy',
    cuisineType: ['Italian'],
    rating: 4.3,
    priceRange: '$$',
    openingHours: {
      opening: '11:30',
      closing: '22:30',
    },
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=80',
    phoneNumber: '555-876-5432',
    email: 'ciao@pastaparadise.com',
    capacity: 70,
    availableForEvents: true,
  }
];

// Mock Menu Items Data
export const mockMenuItems = [
  {
    id: 'menu-1',
    name: 'Classic Burger',
    description: 'Juicy beef patty with lettuce, tomato, and special sauce',
    price: 12.99,
    category: 'mains',
    available: true,
    preparationTime: 15,
    restaurantId: '1',
    inventoryItems: ['inv-1', 'inv-3']
  },
  {
    id: 'menu-2',
    name: 'Caesar Salad',
    description: 'Fresh romaine lettuce with caesar dressing, croutons, and parmesan',
    price: 9.99,
    category: 'starters',
    available: true,
    preparationTime: 10,
    restaurantId: '1',
    inventoryItems: ['inv-2', 'inv-5']
  },
  {
    id: 'menu-3',
    name: 'Cheesecake',
    description: 'Creamy New York style cheesecake with berry compote',
    price: 7.99,
    category: 'desserts',
    available: true,
    preparationTime: 5,
    restaurantId: '1',
    inventoryItems: ['inv-7', 'inv-8']
  },
  {
    id: 'menu-4',
    name: 'Margherita Pizza',
    description: 'Classic pizza with tomato sauce, mozzarella, and basil',
    price: 14.99,
    category: 'mains',
    available: true,
    preparationTime: 20,
    restaurantId: '1',
    inventoryItems: ['inv-4', 'inv-6']
  },
  {
    id: 'menu-5',
    name: 'Garlic Bread',
    description: 'Toasted bread with garlic butter and herbs',
    price: 4.99,
    category: 'sides',
    available: true,
    preparationTime: 8,
    restaurantId: '1',
    inventoryItems: ['inv-6']
  },
  {
    id: 'menu-6',
    name: 'Iced Tea',
    description: 'Refreshing house-brewed iced tea with lemon',
    price: 3.50,
    category: 'drinks',
    available: true,
    preparationTime: 3,
    restaurantId: '1',
    inventoryItems: ['inv-10']
  }
];

// Mock Orders Data
export const mockOrders: Order[] = [
  {
    id: 'ord1',
    restaurantId: '1',
    customerId: 'cust1',
    items: [
      {
        menuItem: mockMenuItems.find(item => item.id === 'menu-1')!,
        quantity: 2,
        specialInstructions: 'Extra parmesan please',
      },
    ],
    status: 'pending',
    totalAmount: 29.98,
    createdAt: '2023-04-15T14:30:00Z',
    tableNumber: 5,
    isDelivery: false,
    paymentStatus: 'pending',
  },
  {
    id: 'ord2',
    restaurantId: '2',
    customerId: 'cust2',
    items: [
      {
        menuItem: mockMenuItems.find(item => item.id === 'menu-2')!,
        quantity: 1,
      },
    ],
    status: 'preparing',
    totalAmount: 16.99,
    createdAt: '2023-04-15T18:45:00Z',
    isDelivery: true,
    deliveryAddress: '123 Customer St, City',
    paymentStatus: 'completed',
  },
  {
    id: 'ord3',
    restaurantId: '4',
    customerId: 'cust3',
    items: [
      {
        menuItem: mockMenuItems.find(item => item.id === 'menu-3')!,
        quantity: 2,
      },
    ],
    status: 'delivered',
    totalAmount: 49.98,
    createdAt: '2023-04-14T19:30:00Z',
    isDelivery: true,
    deliveryAddress: '456 Diner Ave, City',
    paymentStatus: 'completed',
  },
];

// Mock Reservations Data
export const mockReservations: Reservation[] = [
  {
    id: '1',
    restaurantId: '1',
    customerId: 'customer1',
    customerName: 'John Smith',
    customerEmail: 'john@example.com',
    customerPhone: '(123) 456-7890',
    date: '2025-04-28',
    time: '18:30',
    partySize: 4,
    status: 'confirmed',
    tableNumber: 8,
  },
  {
    id: '2',
    restaurantId: '1',
    customerId: 'customer2',
    customerName: 'Sarah Johnson',
    customerEmail: 'sarah@example.com',
    customerPhone: '(234) 567-8901',
    date: '2025-04-28',
    time: '19:00',
    partySize: 2,
    status: 'pending',
    specialRequests: 'Window seating preferred',
  },
  {
    id: '3',
    restaurantId: '1',
    customerId: 'customer3',
    customerName: 'Michael Brown',
    customerEmail: 'michael@example.com',
    customerPhone: '(345) 678-9012',
    date: '2025-04-28',
    time: '20:00',
    partySize: 6,
    status: 'confirmed',
    tableNumber: 12,
    specialRequests: 'Anniversary celebration',
  },
  {
    id: '4',
    restaurantId: '1',
    customerId: 'customer4',
    customerName: 'Jennifer Davis',
    customerEmail: 'jennifer@example.com',
    customerPhone: '(456) 789-0123',
    date: '2025-04-29',
    time: '19:30',
    partySize: 3,
    status: 'confirmed',
    tableNumber: 5,
  },
  {
    id: '5',
    restaurantId: '1',
    customerId: 'customer5',
    customerName: 'Robert Wilson',
    customerEmail: 'robert@example.com',
    customerPhone: '(567) 890-1234',
    date: '2025-04-30',
    time: '18:00',
    partySize: 8,
    status: 'pending',
    specialRequests: 'Birthday celebration, need space for cake',
  },
];

// Mock Inventory Data
export const mockInventoryItems: InventoryItem[] = [
  {
    id: 'inv1',
    name: 'Tomatoes',
    category: 'Vegetables',
    quantity: 25,
    unit: 'kg',
    threshold: 10,
    cost: 4.99,
    restaurantId: '1',
    supplier: 'Local Farm Co.',
    lastRestocked: '2023-04-10',
  },
  {
    id: 'inv2',
    name: 'Chicken Breast',
    category: 'Meat',
    quantity: 15,
    unit: 'kg',
    threshold: 8,
    cost: 9.99,
    restaurantId: '2',
    supplier: 'Premium Meats Inc.',
    lastRestocked: '2023-04-12',
  },
  {
    id: 'inv3',
    name: 'Salmon Fillet',
    category: 'Seafood',
    quantity: 8,
    unit: 'kg',
    threshold: 5,
    cost: 24.99,
    restaurantId: '4',
    supplier: 'Ocean Fresh Seafood',
    lastRestocked: '2023-04-14',
  },
  {
    id: 'inv4',
    name: 'Flour',
    category: 'Dry Goods',
    quantity: 40,
    unit: 'kg',
    threshold: 15,
    cost: 2.49,
    restaurantId: '5',
    supplier: 'Baker\'s Supply Co.',
    lastRestocked: '2023-04-05',
  },
  {
    id: 'inv5',
    name: 'Olive Oil',
    category: 'Oils & Condiments',
    quantity: 12,
    unit: 'L',
    threshold: 6,
    cost: 18.99,
    restaurantId: '1',
    supplier: 'Mediterranean Imports',
    lastRestocked: '2023-04-08',
  },
  {
    id: 'inv6',
    name: 'Garlic',
    category: 'Herbs & Spices',
    quantity: 10,
    unit: 'g',
    threshold: 5,
    cost: 1.99,
    restaurantId: '1',
    supplier: 'Herb & Spice Co.',
    lastRestocked: '2023-04-06',
  },
  {
    id: 'inv7',
    name: 'Strawberries',
    category: 'Fruits',
    quantity: 30,
    unit: 'kg',
    threshold: 15,
    cost: 3.99,
    restaurantId: '1',
    supplier: 'Local Farm Co.',
    lastRestocked: '2023-04-09',
  },
  {
    id: 'inv8',
    name: 'Blueberries',
    category: 'Fruits',
    quantity: 20,
    unit: 'kg',
    threshold: 10,
    cost: 4.99,
    restaurantId: '1',
    supplier: 'Local Farm Co.',
    lastRestocked: '2023-04-11',
  },
  {
    id: 'inv9',
    name: 'Bread',
    category: 'Bakery',
    quantity: 50,
    unit: 'loaves',
    threshold: 20,
    cost: 2.99,
    restaurantId: '1',
    supplier: 'Baker\'s Supply Co.',
    lastRestocked: '2023-04-13',
  },
  {
    id: 'inv10',
    name: 'Tea Bags',
    category: 'Beverages',
    quantity: 100,
    unit: 'bags',
    threshold: 50,
    cost: 1.99,
    restaurantId: '1',
    supplier: 'Tea & Coffee Co.',
    lastRestocked: '2023-04-15',
  }
];
